### ISSUE TITLE
Remove actix-web fork dependency 

### ISSUE THREAD

**Issue by mplebanski** [golemfactory/gumpi#14]
We would like not to depend on a fork that could stop existing some day, but use the original repo instead. There are two things we can do: 

- create a PR to original repository,
- remove dependencies on fork,

and move to original `actix-web` repository.

**Comment by marmistrz** [comment]
@mplebanski the fork is used only for this open patch: https://github.com/actix/actix-web/pull/681

actix-web 0.8 may remove the need for using a fork.

**Comment by mplebanski** [comment]
I see. Is that OK for you to leave this issue opened until this is resolved?

**Comment by marmistrz** [comment]
Yes.
-- 
Sent from my mobile. Please excuse the typos.
